version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: raspberrypi_2b
      buildspec: ./buildspec2.yml
      env:
        variables:
          CHIP: bcm2836
          DEFCONFIG: rpi_2_defconfig
          TUPLE: arm-linux-gnueabihf
    - identifier: raspberrypi_3b
      buildspec: ./buildspec2.yml
      env:
        variables:
          CHIP: bcm2837
          DEFCONFIG: rpi_3_defconfig
          TUPLE: aarch64-linux-gnu
